//! Code tables from the NFIRS 5.0 data dictionary
//! (USFA, `nfirs_spec_tables_2013.xls`, public domain).
//! Generated from the spreadsheet; looked up by linear scan (tables are small).

/// Description for `code`, or "" if unknown. Plus-one codes (a fourth,
/// locally defined digit) fall back to their three-digit national parent.
pub fn describe(table: &'static [(&'static str, &'static str)], code: &str) -> &'static str {
    let code = code.trim();
    let find = |c: &str| table.iter().find(|(k, _)| *k == c).map(|(_, d)| *d);
    find(code)
        .or_else(|| code.get(..3).filter(|_| code.len() == 4).and_then(find))
        .unwrap_or("")
}

pub static INCIDENT_TYPE: &[(&str, &str)] = &[
    ("100", "Fire, other"),
    ("110", "Structure fire, other (conversion only)"),
    ("111", "Building fire"),
    ("112", "Fires in structure other than in a building"),
    ("113", "Cooking fire, confined to container"),
    ("114", "Chimney or flue fire, confined to chimney or flue"),
    ("115", "Incinerator overload or malfunction, fire confined"),
    ("116", "Fuel burner/boiler malfunction, fire confined"),
    ("117", "Commercial Compactor fire, confined to rubbish"),
    ("118", "Trash or rubbish fire, contained"),
    ("120", "Fire in mobile prop. used as a fixed struc., other"),
    ("121", "Fire in mobile home used as fixed residence"),
    ("122", "Fire in motor home, camper, recreational vehicle"),
    ("123", "Fire in portable building, fixed location"),
    ("130", "Mobile property (vehicle) fire, other"),
    ("131", "Passenger vehicle fire"),
    ("132", "Road freight or transport vehicle fire"),
    ("133", "Rail vehicle fire"),
    ("134", "Water vehicle fire"),
    ("135", "Aircraft fire"),
    ("136", "Self-propelled motor home or recreational vehicle"),
    ("137", "Camper or recreational vehicle (RV) fire"),
    ("138", "Off-road vehicle or heavy equipment fire"),
    ("140", "Natural vegetation fire, other"),
    ("141", "Forest, woods or wildland fire"),
    ("142", "Brush or brush-and-grass mixture fire"),
    ("143", "Grass fire"),
    ("150", "Outside rubbish fire, other"),
    ("151", "Outside rubbish, trash or waste fire"),
    ("152", "Garbage dump or sanitary landfill fire"),
    ("153", "Construction or demolition landfill fire"),
    ("154", "Dumpster or other outside trash receptacle fire"),
    ("155", "Outside stationary compactor/compacted trash fire"),
    ("160", "Special outside fire, other"),
    ("161", "Outside storage fire"),
    ("162", "Outside equipment fire"),
    ("163", "Outside gas or vapor combustion explosion"),
    ("164", "Outside mailbox fire"),
    ("170", "Cultivated vegetation, crop fire, other"),
    ("171", "Cultivated grain or crop fire"),
    ("172", "Cultivated orchard or vineyard fire"),
    ("173", "Cultivated trees or nursery stock fire"),
    ("200", "Overpressure rupture, explosion, overheat other"),
    ("210", "Overpressure rupture from steam, other"),
    ("211", "Overpressure rupture of steam pipe or pipeline"),
    ("212", "Overpressure rupture of steam boiler"),
    ("213", "Steam rupture of pressure or process vessel"),
    ("220", "Overpressure rupture from air or gas, other"),
    ("221", "Overpressure rupture of air or gas pipe/pipeline"),
    ("222", "Overpressure rupture of boiler from air or gas"),
    ("223", "Air or gas rupture of pressure or process vessel"),
    ("231", "Chemical reaction rupture of process vessel"),
    ("240", "Explosion (no fire), other"),
    ("241", "Munitions or bomb explosion (no fire)"),
    ("242", "Blasting agent explosion (no fire)"),
    ("243", "Fireworks explosion (no fire)"),
    ("244", "Dust explosion (no fire)"),
    ("251", "Excessive heat, scorch burns with no ignition"),
    ("300", "Rescue, EMS incident, other"),
    ("311", "Medical assist, assist EMS crew"),
    ("320", "Emergency medical service incident, other"),
    ("321", "EMS call, excluding vehicle accident with injury"),
    ("322", "Motor vehicle accident with injuries"),
    ("323", "Motor vehicle/pedestrian accident (MV Ped)"),
    ("324", "Motor vehicle accident with no injuries."),
    ("331", "Lock-in (if lock out , use 511 )"),
    ("340", "Search for lost person, other"),
    ("341", "Search for person on land"),
    ("342", "Search for person in water"),
    ("343", "Search for person underground"),
    ("350", "Extrication, rescue, other"),
    ("351", "Extrication of victim(s) from building/structure"),
    ("352", "Extrication of victim(s) from vehicle"),
    ("353", "Removal of victim(s) from stalled elevator"),
    ("354", "Trench/below-grade rescue"),
    ("355", "Confined space rescue"),
    ("356", "High-angle rescue"),
    ("357", "Extrication of victim(s) from machinery"),
    ("360", "Water & ice-related rescue, other"),
    ("361", "Swimming/recreational water areas rescue"),
    ("362", "Ice rescue"),
    ("363", "Swift water rescue"),
    ("364", "Surf rescue"),
    ("365", "Watercraft rescue"),
    ("370", "Electrical rescue, other"),
    ("371", "Electrocution or potential electrocution"),
    ("372", "Trapped by power lines"),
    ("381", "Rescue or EMS standby"),
    ("400", "Hazardous condition, other"),
    ("410", "Combustible/flammable gas/liquid condition, other"),
    ("411", "Gasoline or other flammable liquid spill"),
    ("412", "Gas leak (natural gas or LPG)"),
    ("413", "Oil or other combustible liquid spill"),
    ("420", "Toxic condition, other"),
    ("421", "Chemical hazard (no spill or leak)"),
    ("422", "Chemical spill or leak"),
    ("423", "Refrigeration leak"),
    ("424", "Carbon monoxide incident"),
    ("430", "Radioactive condition, other"),
    ("431", "Radiation leak, radioactive material"),
    ("440", "Electrical  wiring/equipment problem, other"),
    ("441", "Heat from short circuit (wiring), defective/worn"),
    ("442", "Overheated motor"),
    ("443", "Breakdown of light ballast"),
    ("444", "Power line down"),
    ("445", "Arcing, shorted electrical equipment"),
    ("451", "Biological hazard, confirmed or suspected"),
    ("460", "Accident, potential accident, other"),
    ("461", "Building or structure weakened or collapsed"),
    ("462", "Aircraft standby"),
    ("463", "Vehicle accident, general cleanup"),
    ("471", "Explosive, bomb removal (for bomb scare, use 721)"),
    ("480", "Attempted burning, illegal action, other"),
    ("481", "Attempt to burn"),
    ("482", "Threat to burn"),
    ("500", "Service Call, other"),
    ("510", "Person in distress, other"),
    ("511", "Lock-out"),
    ("512", "Ring or jewelry removal"),
    ("520", "Water problem, other"),
    ("521", "Water evacuation"),
    ("522", "Water or steam leak"),
    ("531", "Smoke or odor removal"),
    ("540", "Animal problem, other"),
    ("541", "Animal problem"),
    ("542", "Animal rescue"),
    ("550", "Public service assistance, other"),
    ("551", "Assist police or other governmental agency"),
    ("552", "Police matter"),
    ("553", "Public service"),
    ("554", "Assist invalid"),
    ("555", "Defective elevator, no occupants"),
    ("561", "Unauthorized burning"),
    ("571", "Cover assignment, standby, moveup"),
    ("600", "Good intent call, other"),
    ("611", "Dispatched & canceled en route"),
    ("621", "Wrong location"),
    ("622", "No incident found on arrival at dispatch address"),
    ("631", "Authorized controlled burning"),
    ("632", "Prescribed fire"),
    ("641", "Vicinity alarm (incident in other location)"),
    ("650", "Steam, other gas mistaken for smoke, other"),
    ("651", "Smoke scare, odor of smoke"),
    ("652", "Steam, vapor, fog or dust thought to be smoke"),
    ("653", "Smoke from barbecue, tar kettle"),
    ("661", "EMS call, party transported by non-fire agency"),
    ("671", "HazMat release investigation w/no HazMat"),
    ("672", "Biological hazard investigation, none found"),
    ("700", "False alarm or false call, other"),
    ("710", "Malicious, mischievous false call, other"),
    ("711", "Municipal alarm system, malicious false alarm"),
    ("712", "Direct tie to FD, malicious false alarm"),
    ("713", "Telephone, malicious false alarm"),
    ("714", "Central station, malicious false alarm"),
    ("715", "Local alarm system, malicious false alarm"),
    ("721", "Bomb scare - no bomb"),
    ("730", "System malfunction, other"),
    ("731", "Sprinkler activation due to malfunction"),
    ("732", "Extinguishing system activation due to malfunction"),
    ("733", "Smoke detector activation due to malfunction"),
    ("734", "Heat detector activation due to malfunction"),
    ("735", "Alarm system sounded due to malfunction"),
    ("736", "CO detector activation due to malfunction"),
    ("740", "Unintentional transmission of alarm, other"),
    ("741", "Sprinkler activation, no fire - unintentional"),
    ("742", "Extinguishing system activation"),
    ("743", "Smoke detector activation, no fire - unintentional"),
    ("744", "Detector activation, no fire - unintentional"),
    ("745", "Alarm system activation, no fire - unintentional"),
    ("746", "Carbon monoxide detector activation, no CO"),
    ("751", "Biological hazard, malicious false report"),
    ("800", "Severe weather or natural disaster, other"),
    ("811", "Earthquake assessment"),
    ("812", "Flood assessment"),
    ("813", "Wind storm, tornado/hurricane assessment"),
    ("814", "Lightning strike (no fire)"),
    ("815", "Severe weather or natural disaster standby"),
    ("900", "Special type of incident, other"),
    ("911", "Citizen complaint"),
    ("UUU", "Undetermined incident type (conversion only)"),
];
pub static AID: &[(&str, &str)] = &[
    ("1", "Mutual aid received"),
    ("2", "Automatic aid received"),
    ("3", "Mutual aid given"),
    ("4", "Automatic aid given"),
    ("5", "Other aid given"),
    ("N", "None"),
];
pub static ACTIONS_TAKEN: &[(&str, &str)] = &[
    ("10", "Fire control or extinguishment, other"),
    ("11", "Extinguishment by fire service personnel"),
    ("12", "Salvage & overhaul"),
    ("13", "Establish fire lines (wildfire)"),
    ("14", "Contain fire (wildland)"),
    ("15", "Confine fire (wildland)"),
    ("16", "Control fire (wildland)"),
    ("17", "Manage prescribed fire (wildland)"),
    ("20", "Search & rescue, other"),
    ("21", "Search"),
    ("22", "Rescue, remove from harm"),
    ("23", "Extricate, disentangle"),
    ("24", "Recover body"),
    ("30", "Emergency medical services, other"),
    ("31", "Provide first aid & check for injuries"),
    ("32", "Provide basic life support (BLS)"),
    ("33", "Provide advanced life support (ALS)"),
    ("34", "Transport person"),
    ("40", "Hazardous condition, other"),
    ("41", "Identify, analyze hazardous materials"),
    ("42", "HazMat detection, monitoring, sampling, & analysis"),
    ("43", "Hazardous materials spill control and confinement"),
    ("44", "Hazardous materials leak control & containment"),
    ("45", "Remove hazard"),
    ("46", "Decontaminate persons or equipment"),
    ("47", "Decontaminate occupancy or area"),
    ("48", "Remove hazardous materials"),
    ("50", "Fires, rescues & hazardous conditions, other"),
    ("51", "Ventilate"),
    ("52", "Forcible entry"),
    ("53", "Evacuate area"),
    ("54", "Determine if materials are non-hazardous"),
    ("55", "Establish safe area"),
    ("56", "Provide air supply"),
    ("57", "Provide light or electrical power"),
    ("58", "Operate apparatus or vehicle"),
    ("60", "Systems and services, other"),
    ("61", "Restore municipal services"),
    ("62", "Restore sprinkler or fire protection system"),
    ("63", "Restore fire alarm system"),
    ("64", "Shut down system"),
    ("65", "Secure property"),
    ("66", "Remove water"),
    ("70", "Assistance, other"),
    ("71", "Assist physically disabled"),
    ("72", "Assist animal"),
    ("73", "Provide manpower"),
    ("74", "Provide apparatus"),
    ("75", "Provide equipment"),
    ("76", "Provide water"),
    ("77", "Control crowd"),
    ("78", "Control traffic"),
    ("79", "Assess severe weather or natural disaster damage"),
    ("80", "Information, investigation & enforcement, other"),
    ("81", "Incident command"),
    ("82", "Notify other agencies."),
    ("83", "Provide information to public or media"),
    ("84", "Refer to proper authority"),
    ("85", "Enforce codes"),
    ("86", "Investigate"),
    ("87", "Investigate fire out on arrival"),
    ("90", "Fill-in, standby, other"),
    ("91", "Fill-in or moveup"),
    ("92", "Standby"),
    ("93", "Cancelled en route"),
    ("00", "Action taken, other"),
    ("UU", "Undetermined (conversion only)"),
];
pub static PROPERTY_USE: &[(&str, &str)] = &[
    ("100", "Assembly, other"),
    ("110", "Fixed-use recreation places, other"),
    ("111", "Bowling establishment"),
    ("112", "Billiard center, pool hall"),
    ("113", "Electronic amusement center"),
    ("114", "Ice rink: indoor, outdoor"),
    ("115", "Roller rink: indoor or outdoor"),
    ("116", "Swimming facility: indoor or outdoor"),
    ("120", "Variable-use amusement, recreation places, other"),
    ("121", "Ballroom, gymnasium"),
    ("122", "Convention center, exhibition hall"),
    ("123", "Stadium, arena"),
    ("124", "Playground"),
    ("129", "Amusement center: indoor/outdoor"),
    ("130", "Places of worship, funeral parlors, other"),
    ("131", "Church, mosque, synagogue, temple, chapel"),
    ("134", "Funeral parlor"),
    ("140", "Clubs, other"),
    ("141", "Athletic/health club"),
    ("142", "Clubhouse"),
    ("143", "Yacht Club"),
    ("144", "Casino, gambling clubs"),
    ("150", "Public or government, other"),
    ("151", "Library"),
    ("152", "Museum"),
    ("154", "Memorial structure, including monuments & statues"),
    ("155", "Courthouse"),
    ("160", "Eating, drinking places, other"),
    ("161", "Restaurant or cafeteria"),
    ("162", "Bar or nightclub"),
    ("170", "Passenger terminal, other"),
    ("171", "Airport passenger terminal"),
    ("173", "Bus station"),
    ("174", "Rapid transit station"),
    ("180", "Studio/theater, other"),
    ("181", "Live performance theater"),
    ("182", "Auditorium, concert hall"),
    ("183", "Movie theater"),
    ("185", "Radio, television studio"),
    ("186", "Film/movie production studio"),
    ("200", "Educational, other"),
    ("210", "Schools, non-adult, other"),
    ("211", "Preschool"),
    ("213", "Elementary school, including kindergarten"),
    ("215", "High school/junior high school/middle school"),
    ("241", "Adult education center, college classroom"),
    ("250", "Day care, other (Conversion only)"),
    ("254", "Day care, in commercial property"),
    ("255", "Day care, in residence, licensed"),
    ("256", "Day care in residence, unlicensed."),
    ("300", "Health care, detention, & correction, other"),
    ("311", "24-hour care Nursing homes, 4 or more persons"),
    ("321", "Mental retardation/development disability facility"),
    ("322", "Alcohol or substance abuse recovery center"),
    ("323", "Asylum, mental institution"),
    ("331", "Hospital - medical or psychiatric"),
    ("332", "Hospices"),
    ("340", "Clinics, doctors offices, hemodialysis cntr, other"),
    ("341", "Clinic, clinic-type infirmary"),
    ("342", "Doctor, dentist or oral surgeon office"),
    ("343", "Hemodialysis unit"),
    ("361", "Jail, prison (not juvenile)"),
    ("363", "Reformatory, juvenile detention center"),
    ("365", "Police station"),
    ("400", "Residential, other"),
    ("419", "1 or 2 family dwelling"),
    ("429", "Multifamily dwelling"),
    ("439", "Boarding/rooming house, residential hotels"),
    ("449", "Hotel/motel, commercial"),
    ("459", "Residential board and care"),
    ("460", "Dormitory-type residence, other"),
    ("462", "Sorority house, fraternity house"),
    ("464", "Barracks, dormitory"),
    ("500", "Mercantile, business, other"),
    ("511", "Convenience store"),
    ("519", "Food and beverage sales, grocery store"),
    ("529", "Textile, wearing apparel sales"),
    ("539", "Household goods, sales, repairs"),
    ("549", "Specialty shop"),
    ("557", "Personal service, including barber & beauty shops"),
    ("559", "Recreational, hobby, home repair sales, pet store"),
    ("564", "Laundry, dry cleaning"),
    ("569", "Professional supplies, services"),
    ("571", "Service station, gas station"),
    ("579", "Motor vehicle or boat sales, services, repair"),
    ("580", "General retail, other"),
    ("581", "Department or discount store"),
    ("592", "Bank"),
    ("593", "Office:  veterinary or research"),
    ("596", "Post office or mailing firms"),
    ("599", "Business office"),
    ("600", "Ind., utility, defense, agriculture, mining, other"),
    ("610", "Energy production plant, other"),
    ("614", "Steam or heat-generating plant"),
    ("615", "Electric-generating plant"),
    ("629", "Laboratory or science laboratory"),
    ("631", "Defense, military installation"),
    ("632", "Flight control tower"),
    ("635", "Computer center"),
    ("639", "Communications center"),
    ("640", "Utility or Distribution system, other"),
    ("642", "Electrical distribution"),
    ("644", "Gas distribution, gas pipeline"),
    ("645", "Flammable liquid distribution, F.L. pipeline"),
    ("647", "Water utility"),
    ("648", "Sanitation utility"),
    ("655", "Crops or orchard"),
    ("659", "Livestock production"),
    ("669", "Forest, timberland, woodland"),
    ("679", "Mine, quarry"),
    ("700", "Manufacturing, processing"),
    ("800", "Storage, other"),
    ("807", "Outside material storage area"),
    ("808", "Outbuilding or shed"),
    ("816", "Grain elevator, silo"),
    ("819", "Livestock, poultry storage"),
    ("839", "Refrigerated storage"),
    ("849", "Outside storage tank"),
    ("880", "Vehicle storage, other"),
    ("881", "Parking garage, (detached residential garage)"),
    ("882", "Parking garage, general vehicle"),
    ("888", "Fire station"),
    ("891", "Warehouse"),
    ("898", "Dock, marina, pier, wharf"),
    ("899", "Residential or self-storage units"),
    ("900", "Outside or special property, other"),
    ("919", "Dump, sanitary landfill"),
    ("921", "Bridge, trestle"),
    ("922", "Tunnel"),
    ("926", "Outbuilding, protective shelter"),
    ("931", "Open land or field"),
    ("935", "Campsite with utilities"),
    ("936", "Vacant lot"),
    ("937", "Beach"),
    ("938", "Graded and cared-for plots of land"),
    ("940", "Water area, other"),
    ("941", "Open ocean, sea or tidal waters"),
    ("946", "Lake, river, stream"),
    ("951", "Railroad right-of-way"),
    ("952", "Railroad yard"),
    ("960", "Street, other"),
    ("961", "Highway or divided highway"),
    ("962", "Residential street, road or residential driveway"),
    ("963", "Street or road in commercial area"),
    ("965", "Vehicle parking area"),
    ("972", "Aircraft runway"),
    ("973", "Aircraft taxiway"),
    ("974", "Aircraft loading area"),
    ("981", "Construction site"),
    ("982", "Oil or gas field"),
    ("983", "Pipeline, power line or other utility right-of-way"),
    ("984", "Industrial plant yard - area"),
    ("000", "Property Use, other"),
    ("NNN", "None"),
    ("UUU", "Undetermined"),
];
